export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_LINE_QUANTITY = "UPDATE_CART_LINE_QUANTITY";
export const REMOVE_SELECTED_FROM_CART = "REMOVE_SELECTED_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const HYDRATE_CART = "HYDRATE_CART";

export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_SUCCESS = "PRODUCTS_SUCCESS";
export const PRODUCTS_FAIL = "PRODUCTS_FAIL";
export const PRODUCT_ARCHIVE_SUCCESS = "PRODUCT_ARCHIVE_SUCCESS";

export const ADMIN_ORDERS_REQUEST = "ADMIN_ORDERS_REQUEST";
export const ADMIN_ORDERS_SUCCESS = "ADMIN_ORDERS_SUCCESS";
export const ADMIN_ORDERS_FAIL = "ADMIN_ORDERS_FAIL";
export const ADMIN_ORDER_STATUS_SUCCESS = "ADMIN_ORDER_STATUS_SUCCESS";

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST";
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS";
export const USER_ORDERS_FAIL = "USER_ORDERS_FAIL";
export const USER_ORDER_STATUS_SUCCESS = "USER_ORDER_STATUS_SUCCESS";

export const MY_REVIEWS_REQUEST = "MY_REVIEWS_REQUEST";
export const MY_REVIEWS_SUCCESS = "MY_REVIEWS_SUCCESS";
export const MY_REVIEWS_FAIL = "MY_REVIEWS_FAIL";
export const MY_REVIEW_DELETE_SUCCESS = "MY_REVIEW_DELETE_SUCCESS";
export const MY_REVIEW_UPSERT_SUCCESS = "MY_REVIEW_UPSERT_SUCCESS";

export const ADMIN_REVIEWS_REQUEST = "ADMIN_REVIEWS_REQUEST";
export const ADMIN_REVIEWS_SUCCESS = "ADMIN_REVIEWS_SUCCESS";
export const ADMIN_REVIEWS_FAIL = "ADMIN_REVIEWS_FAIL";
export const ADMIN_REVIEW_ARCHIVE_SUCCESS = "ADMIN_REVIEW_ARCHIVE_SUCCESS";
export const ADMIN_REVIEWS_BULK_ARCHIVE_SUCCESS = "ADMIN_REVIEWS_BULK_ARCHIVE_SUCCESS";
export const ADMIN_REVIEW_REPLY_SUCCESS = "ADMIN_REVIEW_REPLY_SUCCESS";